name: Teste-push

on:
  pull_request:
    types:
      - closed

jobs:
  teste-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Trigger Push
        run: echo este workflow foi disparado por um pull Request
